(() => {
  "use strict";

  const rawStyles = [
    ["swiss-style", "Swiss Style", "瑞士国际主义风格", "poster", "ruishi", "grid clarity typography"],
    ["bauhaus", "Bauhaus", "包豪斯风格", "poster", "baohaosi", "geometry primary functional"],
    ["art-deco", "Art Deco", "装饰艺术风格", "poster", "zhuangshiyishu", "gold luxury geometric"],
    ["art-nouveau", "Art Nouveau", "新艺术风格", "poster", "xinyishu", "floral organic elegant"],
    ["constructivism", "Constructivism", "构成主义风格", "poster", "gouchengzhuyi", "red diagonal propaganda"],
    ["de-stijl", "De Stijl", "风格派", "poster", "fenggepai", "primary grid abstraction"],
    ["futurism", "Futurism", "未来主义风格", "poster", "weilaizhuyi", "speed motion machine"],
    ["minimalism", "Minimalism", "极简主义风格", "poster", "jijian", "reductive whitespace calm"],
    ["brutalism", "Graphic Brutalism", "粗野主义视觉语汇", "poster", "cuyeyizhuyi", "raw bold anti polish"],
    ["memphis", "Memphis", "孟菲斯风格", "poster", "mengfeisi", "playful pattern color"],
    ["editorial-typography", "Editorial Typography", "编辑排版风格", "poster", "bianjipaiban", "magazine hierarchy type"],
    ["new-wave-typography", "New Wave Typography", "新浪潮字体风格", "poster", "xinlangchao", "experimental type movement"],
    ["punk-diy", "Punk DIY", "朋克拼贴风格", "poster", "pengke", "copy machine collage"],
    ["grunge", "Grunge", "垃圾摇滚风格", "poster", "lajiyaogun", "distressed texture raw"],
    ["psychedelic-poster", "Psychedelic Poster", "迷幻海报风格", "poster", "mihuan", "swirl acid color"],
    ["pop-art-poster", "Pop Art Poster", "波普海报风格", "poster", "bopu", "comic bright repetition"],
    ["corporate-modernism", "Corporate Modernism", "企业现代主义", "poster", "qiye", "clean business systems"],
    ["anti-design", "Anti-Design", "反设计风格", "poster", "fansheji", "chaos rejection rule"],
    ["experimental-typography", "Experimental Typography", "实验字体风格", "poster", "shiyan", "letterform distortion"],
    ["kinetic-poster", "Kinetic Poster", "动态感海报风格", "poster", "dongtaigan", "motion rhythm poster"],
    ["renaissance", "Renaissance", "文艺复兴风格", "painting", "wenyifuxing", "humanism perspective classical"],
    ["baroque", "Baroque", "巴洛克风格", "painting", "baluoke", "drama light movement"],
    ["rococo", "Rococo", "洛可可风格", "painting", "luokeke", "pastel ornate playful"],
    ["neoclassicism", "Neoclassicism", "新古典主义", "painting", "xingudian", "order virtue antique"],
    ["romanticism", "Romanticism", "浪漫主义", "painting", "langman", "emotion nature sublime"],
    ["realism", "Realism", "现实主义", "painting", "xianshi", "ordinary life truthful"],
    ["academic-painting", "Academic Painting", "学院派绘画", "painting", "xueyuanpai", "polished anatomy formal"],
    ["pre-raphaelite", "Pre-Raphaelite", "前拉斐尔派", "painting", "qianlafeier", "detail medieval romance"],
    ["impressionism", "Impressionism", "印象派", "painting", "yinxiangpai", "light brush outdoor"],
    ["post-impressionism", "Post-Impressionism", "后印象派", "painting", "houyinxiang", "color structure emotion"],
    ["van-gogh", "Van Gogh", "梵高式笔触", "master", "fangao", "swirl impasto emotion"],
    ["monet", "Monet", "莫奈式光影", "master", "monai", "mist light water"],
    ["renoir", "Renoir", "雷诺阿式温暖人物", "master", "leinuoa", "warm people soft"],
    ["cezanne", "Cezanne", "塞尚式结构", "master", "saishang", "structure planes volume"],
    ["picasso-cubism", "Picasso / Cubism", "毕加索立体主义", "master", "bijiasuo", "facets multiple viewpoints"],
    ["matisse", "Matisse", "马蒂斯式色块", "master", "madisi", "cutout color rhythm"],
    ["dali", "Dali", "达利式超现实", "master", "dali", "dream surreal precision"],
    ["magritte", "Magritte", "马格利特式观念超现实", "master", "magelite", "concept surreal calm"],
    ["edward-hopper", "Edward Hopper", "霍普式孤独光影", "master", "huopu", "quiet city light"],
    ["gustav-klimt", "Gustav Klimt", "克里姆特式金色装饰", "master", "kelimute", "gold ornament portrait"],
    ["kandinsky", "Kandinsky", "康定斯基式抽象", "master", "kangdingsiji", "abstract music color"],
    ["mondrian", "Mondrian", "蒙德里安式几何", "master", "mengdelian", "grid primary balance"],
    ["pollock", "Pollock", "波洛克式滴画", "master", "boluoke", "drip action field"],
    ["rothko", "Rothko", "罗斯科式色域", "master", "luosike", "color field silence"],
    ["basquiat", "Basquiat", "巴斯奎特式涂鸦表现", "master", "basikui", "graffiti crown raw"],
    ["expressionism", "Expressionism", "表现主义", "modern", "biaoxian", "intense distortion emotion"],
    ["german-expressionism", "German Expressionism", "德国表现主义", "modern", "deguo", "sharp shadow anxiety"],
    ["surrealism", "Surrealism", "超现实主义", "modern", "chaoxianshi", "dream impossible symbols"],
    ["symbolism", "Symbolism", "象征主义", "modern", "xiangzheng", "myth mood signs"],
    ["fauvism", "Fauvism", "野兽派", "modern", "yeshou", "wild color flat"],
    ["dada", "Dada", "达达主义", "modern", "dada", "absurd collage anti art"],
    ["abstract-expressionism", "Abstract Expressionism", "抽象表现主义", "modern", "chouxiang", "gesture scale emotion"],
    ["color-field-painting", "Color Field Painting", "色域绘画", "modern", "seyu", "large color atmosphere"],
    ["op-art", "Op Art", "欧普艺术", "modern", "oupu", "optical pattern vibration"],
    ["conceptual-art", "Conceptual Art", "观念艺术", "modern", "guannian", "idea language context"],
    ["chinese-ink-painting", "Chinese Ink Painting", "中国水墨画", "asian", "shuimo", "ink void brush"],
    ["gongbi", "Gongbi", "工笔画", "asian", "gongbi", "fine line mineral color"],
    ["xieyi", "Xieyi", "写意画", "asian", "xieyi", "expressive brush spirit"],
    ["shanshui", "Shanshui", "山水画风格", "asian", "shanshui", "mountain water void"],
    ["dunhuang-mural", "Dunhuang Mural", "敦煌壁画风格", "asian", "dunhuang", "mural mineral celestial"],
    ["ukiyo-e", "Ukiyo-e", "浮世绘风格", "asian", "fushihui", "woodblock wave flat"],
    ["sumi-e", "Sumi-e", "日本墨绘", "asian", "mohui", "ink minimal zen"],
    ["nihonga", "Nihonga", "日本岩彩画", "asian", "yancai", "mineral color quiet"],
    ["yamato-e", "Yamato-e", "大和绘", "asian", "dahehe", "court narrative color"],
    ["korean-minhwa", "Korean Minhwa", "韩国民画", "asian", "minhua", "folk tiger color"],
    ["indian-miniature", "Indian Miniature", "印度细密画", "asian", "ximi", "miniature palace detail"],
    ["persian-miniature", "Persian Miniature", "波斯细密画", "asian", "bosi", "garden manuscript detail"],
    ["islamic-geometric", "Islamic Geometric", "伊斯兰几何纹样", "asian", "yisilanjijihe", "geometry tile sacred"],
    ["tibetan-thangka", "Tibetan Thangka", "唐卡风格", "asian", "tangka", "sacred mandala mineral"],
    ["thai-temple-mural", "Thai Temple Mural", "泰国寺庙壁画风格", "asian", "taiguo", "temple mural gold"],
    ["byzantine-icon", "Byzantine Icon", "拜占庭圣像风格", "folk", "baizhanting", "icon gold sacred"],
    ["mexican-muralism", "Mexican Muralism", "墨西哥壁画风格", "folk", "moxige", "public mural social"],
    ["aboriginal-dot-painting", "Aboriginal Dot Painting", "澳大利亚原住民点画", "folk", "dianhua", "dot earth map"],
    ["african-tribal-pattern", "West African Textile Pattern", "西非织物纹样", "folk", "feizhou", "rhythm mask pattern"],
    ["native-american-art", "North American Indigenous Art", "北美原住民艺术", "folk", "beimei", "symbol animal earth"],
    ["russian-lubok", "Russian Lubok", "俄罗斯民间版画", "folk", "eluosi", "folk print bold"],
    ["nordic-folk-art", "Nordic Folk Art", "北欧民俗风格", "folk", "beiou", "floral winter craft"],
    ["celtic-art", "Celtic Art", "凯尔特纹样风格", "folk", "kaierte", "knot manuscript pattern"],
    ["madhubani", "Madhubani", "印度马杜巴尼民间画", "folk", "madubani", "folk line filled"],
    ["chinese-new-year-woodblock", "Chinese New Year Woodblock", "年画风格", "folk", "nianhua", "festive woodblock red"],
    ["healing-animation", "Pastoral Hand-drawn Animation", "田园手绘动画语汇", "animation", "zhiyu", "pastoral hand drawn warm"],
    ["cinematic-anime", "Japanese Animated Film Lighting", "日系动画电影光影", "animation", "dianyingriji", "sky city light"],
    ["classic-disney", "Golden Age Hand-drawn Animation", "黄金时代手绘动画", "animation", "tonghua", "musical charm storybook"],
    ["warm-3d-animation", "Warm 3D Animation", "温情三维动画语汇", "animation", "sanwei", "soft material expressive"],
    ["dreamworks-cartoon", "Exaggerated 3D Cartoon Comedy", "夸张三维卡通喜剧语汇", "animation", "katong", "bold character comedy"],
    ["anime", "Anime", "日漫风格", "animation", "riman", "clean line expressive"],
    ["manga", "Manga", "漫画黑白风格", "animation", "manhua", "black white screentone"],
    ["shonen", "Shonen", "少年漫画风格", "animation", "shaonian", "action speed power"],
    ["shojo", "Shojo", "少女漫画风格", "animation", "shaonv", "romance sparkle delicate"],
    ["american-comic-book", "American Comic Book", "美式漫画风格", "animation", "meishi", "bold ink halftone"],
    ["ligne-claire", "Ligne Claire", "清线漫画风格", "illustration", "qingxian", "clear line flat"],
    ["graphic-novel", "Graphic Novel", "图像小说风格", "illustration", "tuxiangxiaoshuo", "cinematic panels mature"],
    ["noir-illustration", "Noir Illustration", "黑色电影插画", "illustration", "heise", "shadow mystery contrast"],
    ["childrens-picture-book", "Children's Picture Book", "儿童绘本风格", "illustration", "ertonghuiben", "gentle simple story"],
    ["editorial-illustration", "Editorial Illustration", "编辑插画风格", "illustration", "bianjichahua", "concept article clean"],
    ["fashion-illustration", "Fashion Illustration", "时装插画风格", "illustration", "shizhuang", "gesture fabric elegance"],
    ["botanical-illustration", "Botanical Illustration", "植物科学插画", "illustration", "zhiwu", "precise botanical plate"],
    ["scientific-illustration", "Scientific Illustration", "科学插画风格", "illustration", "kexue", "diagram accuracy detail"],
    ["isometric-illustration", "Isometric Illustration", "等距插画风格", "illustration", "dengju", "isometric system object"],
    ["flat-illustration", "Flat Vector Illustration", "扁平矢量插画", "illustration", "bianping", "flat shapes friendly"],
    ["cyberpunk", "Cyberpunk", "赛博朋克", "digital", "saibopengke", "neon city dystopia future"],
    ["vaporwave", "Vaporwave", "蒸汽波", "digital", "zhengqibo", "pastel retro internet nostalgia"],
    ["synthwave", "Synthwave", "合成波", "digital", "hechengbo", "neon grid sunset retro"],
    ["y2k", "Y2K", "千禧风格", "digital", "qianxi", "chrome plastic early internet"],
    ["retrofuturism", "Retrofuturism", "复古未来主义", "digital", "fuguweilai", "space age vintage future"],
    ["solarpunk", "Solarpunk", "太阳朋克", "digital", "taiyangpengke", "green future eco technology"],
    ["afrofuturism", "Afrofuturism", "非洲未来主义", "digital", "feizhouweilai", "african diaspora future tech"],
    ["steampunk", "Steampunk", "蒸汽朋克", "digital", "zhengqipengke", "brass gear victorian machine"],
    ["glitch-art", "Glitch Art", "故障艺术", "digital", "guzhangyishu", "signal error datamosh noise"],
    ["pixel-art", "Pixel Art", "像素艺术", "digital", "xiangsuyishu", "8bit sprite retro game"],
    ["voxel-art", "Voxel Art", "体素风格", "digital", "tisufengge", "blocky cube 3d"],
    ["low-poly", "Low Poly", "低多边形", "digital", "diduobianxing", "faceted polygon 3d"],
    ["glassmorphism", "Glassmorphism", "玻璃拟态", "digital", "bolinitai", "frosted glass transparent ui"],
    ["neumorphism", "Neumorphism", "新拟物风格", "digital", "xinniwu", "soft ui embossed shadow"],
    ["claymorphism", "Claymorphism", "黏土风格", "digital", "niantu", "soft 3d rounded clay"],
    ["holographic", "Holographic", "镭射全息风格", "digital", "leishequanxi", "iridescent hologram rainbow"],
    ["liquid-metal", "Liquid Metal", "液态金属风格", "digital", "yetai jinshu", "chrome fluid metallic"],
    ["3d-abstract-cgi", "3D Abstract CGI", "三维抽象", "digital", "sanweichouxiang", "abstract render material"],
    ["fractal-art", "Fractal Art", "分形艺术", "digital", "fenxingyishu", "recursive algorithm pattern"],
    ["generative-ai-dreamlike", "Generative AI Dreamlike", "AI 梦境风格", "digital", "ai mengjing", "dreamlike surreal generative"]
  ];

  window.STYLE_ATLAS_DATA = Object.assign(window.STYLE_ATLAS_DATA || {}, { rawStyles });
})();
